=== Design-Party-Program/dpo-voyager/source/common/schema/presentation.schema.json
{
    "$id": "https://schemas.3d.si.edu/public_api/presentation.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",

    "title": "Smithsonian 3D Presentation",
    "description": "Describes a 3D scene containing one or multiple 3D items.",

    "definitions": {
        "node": {
            "$id": "#node",
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "description": "The indices of this node's children.",
                    "items": {
                        "type": "integer",
                        "minimum": 0
                    },
                    "uniqueItems": true,
                    "minItems": 1
                },

                "matrix": {
                    "description": "A floating-point 4x4 transformation matrix stored in column-major order.",
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "minItems": 16,
                    "maxItems": 16,
                    "default": [ 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0 ]
                },
                "translation": {
                    "description": "The node's translation along the x, y, and z axes.",
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "minItems": 3,
                    "maxItems": 3,
                    "default": [ 0.0, 0.0, 0.0 ]
                },
                "rotation": {
                    "description": "The node's unit quaternion rotation in the order (x, y, z, w), where w is the scalar.",
                    "type": "array",
                    "items": {
                        "type": "number",
                        "minimum": -1.0,
                        "maximum": 1.0
                    },
                    "minItems": 4,
                    "maxItems": 4,
                    "default": [ 0.0, 0.0, 0.0, 1.0 ]
                },
                "scale": {
                    "description": "The node's non-uniform scale, given as the scaling factors along the x, y, and z axes.",
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "minItems": 3,
                    "maxItems": 3,
                    "default": [ 1.0, 1.0, 1.0 ]
                },

                "item": {
                    "description": "The index of the item in this node.",
                    "type": "integer",
                    "minimum": 0
                },
                "reference": {
                    "description": "The index of the reference in this node.",
                    "type": "integer",
                    "minimum": 0
                },
                "camera": {
                    "description": "The index of the camera in this node.",
                    "type": "integer",
                    "minimum": 0
                },
                "light": {
                    "description": "The index of the light in this node.",
                    "type": "integer",
                    "minimum": 0
                }
            },
            "not": {
                "anyOf": [
                    { "required": [ "matrix", "translation" ] },
                    { "required": [ "matrix", "rotation" ] },
                    { "required": [ "matrix", "scale" ] }
                ]
            }
        },
        "reference": {
            "$id": "#reference",
            "type": "object",
            "properties": {
                "mimeType": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            },
            "required": [
                "uri"
            ]
        },
        "camera": {
            "$id": "#camera",
            "type": "object",
            "properties": {
                "type": {
                    "description": "Specifies if the camera uses a perspective or orthographic projection.",
                    "type": "string",
                    "enum": [
                        "perspective",
                        "orthographic"
                    ]
                },
                "perspective": {
                    "description": "A perspective camera containing properties to create a perspective projection matrix.",
                    "type": "object",
                    "properties": {
                        "yfov": {
                            "type": "number",
                            "description": "The floating-point vertical field of view in radians.",
                            "exclusiveMinimum": 0.0
                        },
                        "aspectRatio": {
                            "type": "number",
                            "description": "The floating-point aspect ratio of the field of view.",
                            "exclusiveMinimum": 0.0
                        },
                        "znear": {
                            "type": "number",
                            "description": "The floating-point distance to the near clipping plane.",
                            "exclusiveMinimum": 0.0
                        },
                        "zfar": {
                            "type": "number",
                            "description": "The floating-point distance to the far clipping plane.",
                            "exclusiveMinimum": 0.0
                        }
                    },
                    "required": [
                        "yfov",
                        "znear"
                    ]
                },
                "orthographic": {
                    "description": "An orthographic camera containing properties to create an orthographic projection matrix.",
                    "type": "object",
                    "properties": {
                        "xmag": {
                            "type": "number",
                            "description": "The floating-point horizontal magnification of the view. Must not be zero."
                        },
                        "ymag": {
                            "type": "number",
                            "description": "The floating-point vertical magnification of the view. Must not be zero."
                        },
                        "znear": {
                            "type": "number",
                            "description": "The floating-point distance to the near clipping plane.",
                            "exclusiveMinimum": 0.0
                        },
                        "zfar": {
                            "type": "number",
                            "description": "The floating-point distance to the far clipping plane. `zfar` must be greater than `znear`.",
                            "exclusiveMinimum": 0.0
                        }
                    },
                    "required": [
                        "xmag",
                        "ymag",
                        "znear",
                        "zfar"
                    ]
                }
            },
            "required": [
                "type"
            ],
            "not": {
                "required": [ "perspective", "orthographic" ]
            }
        },
        "light": {
            "$id": "#light",
            "type": "object",
            "properties": {
                "type": {
                    "description": "Specifies the type of the light source.",
                    "type": "string",
                    "enum": [
                        "ambient",
                        "directional",
                        "point",
                        "spot",
                        "hemisphere"
                    ]
                },
                "color": {
                    "$ref": "#colorRGB"
                },
                "intensity": {
                    "type": "number",
                    "minimum": 0,
                    "default": 1
                },
                "castShadow": {
                    "type": "boolean",
                    "default": false
                },
                "point": {
                    "type": "object",
                    "properties": {
                        "distance": {
                            "type": "number",
                            "minimum": 0
                        },
                        "decay": {
                            "type": "number",
                            "minimum": 0
                        }
                    }
                },
                "spot": {
                    "type": "object",
                    "properties": {
                        "distance": {
                            "type": "number",
                            "minimum": 0
                        },
                        "decay": {
                            "type": "number",
                            "minimum": 0
                        },
                        "angle": {
                            "type": "number",
                            "minimum": 0
                        },
                        "penumbra": {
                            "type": "number",
                            "minimum": 0
                        }
                    }
                },
                "hemisphere": {
                    "type": "object",
                    "properties": {
                        "groundColor": {
                            "$ref": "#colorRGB"
                        }
                    }
                }
            },
            "required": [
                "type"
            ],
            "not": {
                "required": [ "point", "spot", "hemisphere" ]
            }
        },
        "colorRGB": {
            "$id": "#colorRGB",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
            },
            "minItems": 3,
            "maxItems": 3,
            "default": [ 1.0, 1.0, 1.0 ]
        }
    },

    "type": "object",
    "properties": {
        "asset": {
            "type": "object",
            "properties": {
                "copyright": {
                    "type": "string",
                    "description": "A copyright message to credit the content creator."
                },
                "generator": {
                    "type": "string",
                    "description": "Tool that generated this presentation description."
                },
                "version": {
                    "type": "string",
                    "description": "Version of this presentation description."
                }
            }
        },
        "scene": {
            "description": "The root nodes of the scene.",
            "type": "object",
            "properties": {
                "nodes": {
                    "description": "The indices of each root node.",
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "minimum": 0
                    },
                    "uniqueItems": true,
                    "minItems": 1
                }
            },
            "minItems": 1
        },
        "nodes": {
            "description": "An array of nodes.",
            "type": "array",
            "items": {
                "$ref": "#node"
            },
            "minItems": 1
        },
        "items": {
            "description": "An array if items.",
            "type": "array",
            "items": {
                "$ref": "item.schema.json"
            },
            "minItems": 1
        },
        "references": {
            "description": "An array of references.",
            "type": "array",
            "items": {
                "$ref": "#reference"
            },
            "minItems": 1
        },
        "cameras": {
            "description": "An array of cameras.",
            "type": "array",
            "items": {
                "$ref": "#camera"
            },
            "minItems": 1
        },
        "lights": {
            "description": "An array of lights.",
            "type": "array",
            "items": {
                "$ref": "#light"
            },
            "minItems": 1
        },
        "story": {
            "description": "Presentation-level tours and snapshots",
            "$ref": "story.schema.json"
        },
        "config": {
            "description": "Voyager explorer global settings.",
            "$ref": "config.schema.json"
        }
    },
    "required": [
        "scene",
        "nodes"
    ]
}

=== Design-Party-Program/dpo-voyager/source/client/core/templates/presentation.json
{
    "asset": {
        "version": "1.0",
        "copyright": "Copyright 2018 Smithsonian Institution",
        "generator": "Voyager Prep"
    },
    "scene": {
        "nodes": [
            0,
            1
        ]
    },
    "nodes": [
        {
            "translation": [ 0, 0, 50 ],
            "camera": 0
        },
        {
            "name": "Lights",
            "children": [ 2, 3, 4, 5 ]
        },
        {
            "translation": [ -2, 1, 2 ],
            "light": 0
        },
        {
            "translation": [ 2, 1, 2 ],
            "light": 1
        },
        {
            "translation": [ 0, 2, -0.5 ],
            "light": 2
        },
        {
            "translation": [ 0, -2, -1.2 ],
            "light": 3
        }
    ],
    "cameras": [
        {
            "type": "perspective",
            "perspective": {
                "yfov": 50,
                "znear": 0.001,
                "zfar": 10000
            }
        }
    ],
    "lights": [
        {
            "type": "directional",
            "color": [ 1, 1, 1 ],
            "intensity": 1
        },
        {
            "type": "directional",
            "color": [ 1, 1, 1 ],
            "intensity": 1
        },
        {
            "type": "directional",
            "color": [ 1, 0.95, 0.85 ],
            "intensity": 0.5
        },
        {
            "type": "directional",
            "color": [ 0.8, 0.85, 1 ],
            "intensity": 1.0
        }
    ]
}
